#!/bin/bash

echo "🚀 ShareConnect 2.0 - GitHub Push Script"
echo "========================================"
echo ""
echo "This script will help you push ShareConnect to your GitHub repository:"
echo "https://github.com/23se02cb064/shareconnect.2.0.git"
echo ""
echo "Steps to push to GitHub:"
echo ""
echo "1. Make sure you have Git configured with your credentials:"
echo "   git config --global user.name \"Your Name\""
echo "   git config --global user.email \"your.email@example.com\""
echo ""
echo "2. If you have GitHub CLI installed, authenticate:"
echo "   gh auth login"
echo ""
echo "3. Or use a personal access token:"
echo "   git remote set-url origin https://YOUR_TOKEN@github.com/23se02cb064/shareconnect.2.0.git"
echo ""
echo "4. Then push the code:"
echo "   git push -u origin main"
echo ""
echo "Current repository status:"
git status --short
echo ""
echo "Ready to push commits:"
git log --oneline -3
echo ""
echo "🎉 Your ShareConnect 2.0 project is ready for GitHub!"
